export interface PresetService {
  id: string
  name: string
  icon: string
  description: string
  domains: string[]
}

export interface PresetCategory {
  id: string
  name: string
  icon: string
  services: PresetService[]
}

export const PRESET_CATEGORIES: PresetCategory[] = [
  {
    id: 'ai',
    name: 'Искусственный интеллект & LLM',
    icon: '🤖',
    services: [
      {
        id: 'chatgpt',
        name: 'ChatGPT / OpenAI',
        icon: '🟢',
        description: 'ChatGPT, API OpenAI, генератор изображений DALL-E и видео Sora',
        domains: ['chatgpt.com', 'openai.com', 'oaistatic.com', 'oaiusercontent.com', 'auth0.openai.com'],
      },
      {
        id: 'claude',
        name: 'Claude / Anthropic',
        icon: '🟣',
        description: 'Чат Claude 3.5 Sonnet / Opus и веб-портал Anthropic API',
        domains: ['claude.ai', 'anthropic.com'],
      },
      {
        id: 'gemini',
        name: 'Google Gemini & AI Studio',
        icon: '✨',
        description: 'Gemini Web, Google AI Studio, MakerSuite API, DeepMind',
        domains: ['gemini.google.com', 'aistudio.google.com', 'makersuite.google.com', 'deepmind.google', 'flow.google.com'],
      },
      {
        id: 'copilot',
        name: 'Microsoft Copilot',
        icon: '🔷',
        description: 'Microsoft Copilot, Bing AI и сопутствующие службы аутентификации',
        domains: ['copilot.microsoft.com', 'bing.com', 'sydney.bing.com'],
      },
      {
        id: 'perplexity',
        name: 'Perplexity AI',
        icon: '⚡',
        description: 'Поисковая нейросеть Perplexity и AI-ответы',
        domains: ['perplexity.ai', 'pplx.ai'],
      },
      {
        id: 'grok',
        name: 'Grok / xAI',
        icon: '🚀',
        description: 'Нейросеть Grok от xAI и портал разработчиков',
        domains: ['x.ai', 'grok.com'],
      },
      {
        id: 'midjourney',
        name: 'Midjourney',
        icon: '🎨',
        description: 'Веб-генератор Midjourney и галерея артов',
        domains: ['midjourney.com'],
      },
      {
        id: 'suno',
        name: 'Suno AI',
        icon: '🎵',
        description: 'Генератор музыки и вокала Suno',
        domains: ['suno.com', 'suno.ai'],
      },
      {
        id: 'cursor',
        name: 'Cursor IDE & AI',
        icon: '💻',
        description: 'AI-редактор кода Cursor, API и обновление моделей',
        domains: ['cursor.com', 'cursor.sh', 'cursorapi.com'],
      },
      {
        id: 'huggingface',
        name: 'Hugging Face',
        icon: '🤗',
        description: 'Хаб нейросетевых моделей, датасетов и Spaces',
        domains: ['huggingface.co', 'hf.co'],
      },
      {
        id: 'mistral',
        name: 'Mistral AI / Le Chat',
        icon: '🌪️',
        description: 'Европейская языковая модель Mistral и веб-чат',
        domains: ['mistral.ai', 'chat.mistral.ai'],
      },
    ],
  },
  {
    id: 'media',
    name: 'Стриминг & Медиа',
    icon: '🎬',
    services: [
      {
        id: 'youtube',
        name: 'YouTube',
        icon: '▶️',
        description: 'Видеосерверы YouTube (Googlevideo CDN, превью, стримы)',
        domains: ['youtube.com', 'googlevideo.com', 'ytimg.com', 'youtu.be', 'youtubei.googleapis.com'],
      },
      {
        id: 'netflix',
        name: 'Netflix',
        icon: '🍿',
        description: 'Фильмы, сериалы и видео-CDN Netflix',
        domains: ['netflix.com', 'nflxvideo.net', 'nflxext.com', 'nflximg.net'],
      },
      {
        id: 'spotify',
        name: 'Spotify',
        icon: '🎵',
        description: 'Музыкальный стриминг и веб-плеер Spotify',
        domains: ['spotify.com', 'scdn.co', 'spoti.fi'],
      },
      {
        id: 'twitch',
        name: 'Twitch',
        icon: '👾',
        description: 'Прямые трансляции Twitch и стриминг-серверы',
        domains: ['twitch.tv', 'ttvnw.net', 'jtvnw.net'],
      },
      {
        id: 'soundcloud',
        name: 'SoundCloud',
        icon: '☁️',
        description: 'Аудиохостинг SoundCloud и медиа-CDN',
        domains: ['soundcloud.com', 'sndcdn.com'],
      },
      {
        id: 'apple_media',
        name: 'Apple Music & TV+',
        icon: '🍎',
        description: 'Музыкальный сервис Apple Music и видеопотоки Apple TV+',
        domains: ['music.apple.com', 'tv.apple.com', 'apple-dns.net'],
      },
      {
        id: 'deezer',
        name: 'Deezer',
        icon: '🎧',
        description: 'Стриминг музыки Deezer в lossless качестве',
        domains: ['deezer.com', 'dzcdn.net'],
      },
      {
        id: 'tiktok',
        name: 'TikTok',
        icon: '📱',
        description: 'Видеоплатформа TikTok, CDN и лента',
        domains: ['tiktok.com', 'tiktokcdn.com', 'byteoversea.com', 'ibytedtos.com'],
      },
      {
        id: 'pinterest',
        name: 'Pinterest',
        icon: '📌',
        description: 'Визуальный каталог идей Pinterest и галерея пинов',
        domains: ['pinterest.com', 'pinimg.com'],
      },
      {
        id: 'vimeo',
        name: 'Vimeo',
        icon: '📹',
        description: 'Видеохостинг высокого разрешения Vimeo',
        domains: ['vimeo.com', 'vimeocdn.com'],
      },
    ],
  },
  {
    id: 'gaming',
    name: 'Игры & Коммуникации',
    icon: '🎮',
    services: [
      {
        id: 'discord',
        name: 'Discord',
        icon: '💬',
        description: 'Голосовые каналы Discord, текст, медиа и шлюзы',
        domains: ['discord.com', 'discordapp.com', 'discord.gg', 'discordapp.net', 'discord.media'],
      },
      {
        id: 'telegram',
        name: 'Telegram (Звонки & Медиа)',
        icon: '✈️',
        description: 'Звонки, голосовые чаты и быстрая загрузка медиа Telegram',
        domains: ['t.me', 'telegram.org', 'telesco.pe'],
      },
      {
        id: 'whatsapp',
        name: 'WhatsApp Web',
        icon: '📞',
        description: 'Веб-версия WhatsApp и передача медиафайлов',
        domains: ['whatsapp.com', 'whatsapp.net'],
      },
      {
        id: 'steam',
        name: 'Steam Community',
        icon: '🚂',
        description: 'Сообщество Steam, мастерская, профили и торговая площадка',
        domains: ['steamcommunity.com', 'steampowered.com', 'steamstatic.com'],
      },
      {
        id: 'epicgames',
        name: 'Epic Games Store',
        icon: '⚡',
        description: 'Магазин Epic Games и лаунчер Unreal Engine',
        domains: ['epicgames.com', 'unrealengine.com'],
      },
      {
        id: 'playstation',
        name: 'PlayStation Network (PSN)',
        icon: '🎮',
        description: 'Сетевые сервисы Sony PlayStation и магазин PS Store',
        domains: ['playstation.com', 'sonyentertainmentnetwork.com', 'playstation.net'],
      },
      {
        id: 'xbox',
        name: 'Xbox Live & Game Pass',
        icon: '🟢',
        description: 'Сервисы Microsoft Xbox Live, Game Pass и обход ошибки входа 0x80a40401',
        domains: [
          'xbox.com',
          'xboxlive.com',
          'gamepass.com',
          'user.auth.xboxlive.com',
          'device.auth.xboxlive.com',
          'title.auth.xboxlive.com',
          'xsts.auth.xboxlive.com',
        ],
      },
      {
        id: 'supercell',
        name: 'Supercell (Brawl Stars)',
        icon: '👑',
        description: 'Brawl Stars, Clash of Clans, Clash Royale — обход блокировки по IP',
        domains: ['supercell.com', 'supercellid.com', 'brawlstars.com', 'brawlstarsgame.com', 'clashofclans.com', 'clashroyale.com'],
      },
      {
        id: 'nintendo',
        name: 'Nintendo Online',
        icon: '🔴',
        description: 'Магазин Nintendo Switch eShop и сетевые службы',
        domains: ['nintendo.com', 'nintendo.net', 'nintendo.eu'],
      },
      {
        id: 'battlenet',
        name: 'Battle.net / Blizzard',
        icon: '❄️',
        description: 'Лаунчер Blizzard Battle.net (WoW, Diablo, Overwatch)',
        domains: ['battle.net', 'blizzard.com'],
      },
      {
        id: 'riot',
        name: 'Riot Games (Valorant / LoL)',
        icon: '⚔️',
        description: 'Сетевые сервисы Riot Games, античит Vanguard и League of Legends',
        domains: ['riotgames.com', 'leagueoflegends.com', 'pvp.net'],
      },
      {
        id: 'ea',
        name: 'EA App / Origin',
        icon: '🏆',
        description: 'Магазин Electronic Arts (FIFA, Battlefield, Apex Legends)',
        domains: ['ea.com', 'origin.com'],
      },
      {
        id: 'roblox',
        name: 'Roblox',
        icon: '🧱',
        description: 'Игровая метавселенная Roblox и серверы ассетов',
        domains: ['roblox.com', 'rbxcdn.com'],
      },
    ],
  },
  {
    id: 'censorship',
    name: 'Популярные ресурсы & Трекеры',
    icon: '🌐',
    services: [
      {
        id: 'rutracker',
        name: 'RuTracker',
        icon: '📦',
        description: 'Крупнейший торрент-трекер RuTracker и постеры',
        domains: ['rutracker.org', 'rutracker.net', 'rutracker.cc'],
      },
      {
        id: 'ntc',
        name: 'NTC Party',
        icon: '🛡️',
        description: 'Форум NTC.party (новости блокировок и обхода ТСПУ)',
        domains: ['ntc.party'],
      },
      {
        id: 'flibusta',
        name: 'Флибуста',
        icon: '📚',
        description: 'Книжное братство Флибуста',
        domains: ['flibusta.is', 'flibusta.site'],
      },
      {
        id: 'kinozal',
        name: 'Кинозал ТВ',
        icon: '🎥',
        description: 'Трекер Кинозал.ТВ',
        domains: ['kinozal.tv', 'kinozal.me'],
      },
      {
        id: 'rutor',
        name: 'Rutor',
        icon: '🧲',
        description: 'Открытый трекер Rutor',
        domains: ['rutor.info', 'rutor.is'],
      },
      {
        id: 'nnmclub',
        name: 'NNM-Club',
        icon: '💿',
        description: 'Торрент-портал NoNaMe Club',
        domains: ['nnmclub.to', 'nnm-club.me'],
      },
      {
        id: 'lostfilm',
        name: 'LostFilm',
        icon: '🍿',
        description: 'Сериальный портал LostFilm.TV',
        domains: ['lostfilm.tv', 'lostfilm.today'],
      },
      {
        id: 'hdrezka',
        name: 'HDRezka',
        icon: '🎬',
        description: 'Онлайн-кинотеатр HDRezka',
        domains: ['rezka.ag', 'hdrzk.org'],
      },
      {
        id: 'twitter',
        name: 'Twitter / X',
        icon: '🐦',
        description: 'Социальная сеть X (Twitter), картинки и медиа',
        domains: ['x.com', 'twitter.com', 'twimg.com', 't.co'],
      },
      {
        id: 'instagram',
        name: 'Instagram',
        icon: '📸',
        description: 'Instagram фото, видео и CDN-серверы',
        domains: ['instagram.com', 'cdninstagram.com'],
      },
      {
        id: 'facebook',
        name: 'Facebook & Threads',
        icon: '👥',
        description: 'Социальные сети Facebook, Threads и инфраструктура Meta',
        domains: ['facebook.com', 'fbcdn.net', 'threads.net'],
      },
      {
        id: 'linkedin',
        name: 'LinkedIn',
        icon: '💼',
        description: 'Деловая социальная сеть LinkedIn',
        domains: ['linkedin.com', 'licdn.com'],
      },
      {
        id: 'reddit',
        name: 'Reddit',
        icon: '🤖',
        description: 'Сообщество Reddit, обсуждения и медиа',
        domains: ['reddit.com', 'redd.it', 'redditstatic.com'],
      },
      {
        id: 'medium',
        name: 'Medium',
        icon: '📝',
        description: 'Издательская платформа и блоги Medium',
        domains: ['medium.com'],
      },
    ],
  },
  {
    id: 'dev',
    name: 'Разработка & IT-сервисы',
    icon: '⚙️',
    services: [
      {
        id: 'github',
        name: 'GitHub',
        icon: '🐙',
        description: 'Платформа разработки GitHub, репозитории, Gists и ассеты',
        domains: ['github.com', 'githubassets.com', 'githubusercontent.com', 'raw.githubusercontent.com'],
      },
      {
        id: 'gitlab',
        name: 'GitLab',
        icon: '🦊',
        description: 'DevOps-платформа GitLab Cloud',
        domains: ['gitlab.com'],
      },
      {
        id: 'docker',
        name: 'Docker Hub',
        icon: '🐳',
        description: 'Реестр контейнеров Docker Hub и образы',
        domains: ['docker.com', 'docker.io'],
      },
      {
        id: 'npm',
        name: 'npm & Yarn',
        icon: '📦',
        description: 'Реестр пакетов JavaScript npmjs и Yarn',
        domains: ['npmjs.com', 'yarnpkg.com'],
      },
      {
        id: 'cloudflare',
        name: 'Cloudflare',
        icon: '☁️',
        description: 'Панель управления Cloudflare и защищенный DNS',
        domains: ['cloudflare.com', 'cloudflare-dns.com'],
      },
      {
        id: 'notion',
        name: 'Notion',
        icon: '📓',
        description: 'Рабочее пространство Notion, базы данных и заметки',
        domains: ['notion.so', 'notion.site'],
      },
      {
        id: 'canva',
        name: 'Canva',
        icon: '🎨',
        description: 'Онлайн-редактор дизайна Canva',
        domains: ['canva.com'],
      },
      {
        id: 'figma',
        name: 'Figma',
        icon: '📐',
        description: 'Векторный интерфейсный редактор Figma',
        domains: ['figma.com'],
      },
    ],
  },
  {
    id: 'crypto',
    name: 'Криптовалюты & Финансы',
    icon: '🪙',
    services: [
      {
        id: 'binance',
        name: 'Binance',
        icon: '🟡',
        description: 'Криптовалютная биржа Binance и веб-интерфейс',
        domains: ['binance.com', 'bnapp.org', 'binance.cloud'],
      },
      {
        id: 'bybit',
        name: 'Bybit',
        icon: '🟠',
        description: 'Торговая площадка Bybit и фьючерсы',
        domains: ['bybit.com', 'bybit-global.com'],
      },
      {
        id: 'okx',
        name: 'OKX',
        icon: '⬛',
        description: 'Криптобиржа OKX и Web3-кошелек',
        domains: ['okx.com'],
      },
      {
        id: 'tradingview',
        name: 'TradingView',
        icon: '📈',
        description: 'Графики финансовых рынков и котировки TradingView',
        domains: ['tradingview.com'],
      },
      {
        id: 'coinmarketcap',
        name: 'CoinMarketCap',
        icon: '📊',
        description: 'Аналитика и курсы криптовалют CoinMarketCap',
        domains: ['coinmarketcap.com'],
      },
    ],
  },
]
